# src/queue_framework/analysis/__init__.py

"""
Initializes the 'analysis' sub-package.

This package provides optional utilities for plotting and visualizing
KPI data generated by the core framework.

This sub-package requires optional dependencies (matplotlib, seaborn, pandas)
which are not part of the core installation.
"""

import logging

log = logging.getLogger(__name__)

# Graceful Handling of Optional Dependencies
# We wrap the imports in a try...except block.
# If the user has not installed the 'analysis' extras,
# this package will simply appear empty, without crashing
# the core 'queue_framework' import.

try:
    # "Lift" the plotting functions from the plotting module
    # to this package's top level.
    from .plotting import (
        plot_wait_time_histogram,
        plot_system_time_histogram,
        plot_queue_length_over_time,
        plot_server_utilization_over_time,
        plot_transient_analysis,
        plot_batch_means_over_time
    )

    from .transient import (
        calculate_transient_data,
        find_transient_end
    )

    # Define the public API of this sub-package
    __all__ = [
        "plot_wait_time_histogram",
        "plot_system_time_histogram",
        "plot_queue_length_over_time",
        "plot_server_utilization_over_time",
        "plot_transient_analysis",
        "plot_batch_means_over_time",

        "calculate_transient_data",
        "find_transient_end"
    ]

except ImportError:
    # This block executes if matplotlib, seaborn, or pandas are missing.
    log.warning(
        "Optional dependencies for 'queue_framework.analysis' not found. "
        "Plotting functions will be unavailable. "
        "To install, run: pip install queue-framework[analysis]"
    )
    
    # Define an empty public API
    __all__ = []